apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-app
  namespace: movie-catalog
  labels:
    app: movie-catalog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-catalog-app
  template:
    metadata:
      labels:
        app: movie-catalog-app
    spec:
      containers:
        - name: movie-catalog-app
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/movie-catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
